---
title: "Project Study - LASSO Variable Selection"
author: "Helena Zappe & Marei Göbelbecker"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install-packages, eval=FALSE, include=FALSE}

# Download Packages

install.packages(c(
  "tidyverse",  
  "skimr",      
  "psych",      
  "rmarkdown",  
  "knitr",      
  "tinytex",    
  "labelled",
  "here"
  ))
tinytex::install_tinytex()  
```

```{r load_packages, include=FALSE}

# Load Packages

library(haven)
library(tidyverse)   
library(glmnet)
library(skimr)       
library(psych)       
library(rmarkdown)   
library(knitr)       
library(tinytex)     
library(labelled)
library(dplyr)
library(here)
library(tidyr)
library(purrr)

```

```{r raw_data, include=FALSE}

# 1. Lade Daten und entferne nicht benötigte Variablen
dt_all <- read_sav(here("data", "ESS_all.sav")) %>%
  select(-c(trstun))
```

```{r}
# winsurize education years to get rid of outliers
# Calculate thresholds
q_lower <- quantile(dt_all$eduyrs, 0.05, na.rm = TRUE)
q_upper <- quantile(dt_all$eduyrs, 0.99, na.rm = TRUE)

# Winsorize: replace values outside bounds
dt_all <- dt_all %>%
  mutate(eduyrs_winsor = case_when(
    eduyrs < q_lower ~ q_lower,
    eduyrs > q_upper ~ q_upper,
    TRUE ~ eduyrs
  ))
```

# "What shapes trust in the European Union in Poland, Germany, and Slovenia? A comparative analysis of political attitudes, ideology, and socio-demographics."

# LASSO to find best variables

```{r}
# Step 1: Preparing Data for Lasso
# using the gilmnet package
  

# filter variables with too many NAs:
dt_filtered <- dt_all %>%
  drop_na(trstep) %>% # keep only valid observations in y
  select(where(~ !all(is.na(.)))) %>% # 100% NAs
  select(where(~ mean(is.na(.)) <= 0.8)) %>% # keep variables with less than 80% NAs
  select(-c(feethngr, loylead, lrnobed, donprty, volunfp, pbldmna, implvdm)) %>% # these variables are not relevant enough for imputation. Also households net income has 79% NAs and is therefore not meaningful. 
  select(-c(idno, proddate, bctprd, wrkorg, stratum, edition)) # Other variables that are not relevant for interpretation

# checking for missing variables in percent
dt_filtered %>%
  summarise(across(everything(), ~ mean(is.na(.)) * 100)) %>%
  pivot_longer(everything(), names_to = "variable", values_to = "missing_pct") %>%
  filter(missing_pct > 20) %>%
  arrange(missing_pct)

# accounting for differences in country size and selection
dt_filtered <- dt_filtered %>% drop_na(anweight) # dropping all obs where anweight is NA
weights <- dt_filtered$anweight # establishing the weighting

# defining the response Variable
y <- as.numeric(as_factor(dt_filtered$trstep))
table(y, useNA = "always")

# define the predictor variable matrix
x_data <- dt_filtered %>%
  select(-c(trstep, anweight, pspwght, dweight, pweight, prob)) %>%
  zap_labels() %>%  # delete all labels
  mutate(across(where(is.factor), ~ as.numeric(as.character(.)))) # define all factor variables also as numeric

x_data[is.na(x_data)] <- 0  # replaces all NA in x_data

# define the matrix of response variables
x <- data.matrix(x_data)

# LASSO with Crossvalidation and weighting
lasso_cv <- cv.glmnet(x, y, alpha = 1, weights = weights)

```
